# Generated by Django 5.0.4 on 2024-04-27 13:40

import api.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message="Incorrect name. Names can only contain alphabets, '-' and (space)", regex='^[A-Za-z]{2}(?:[-\\s]?[A-Za-z]+)*$')])),
                ('last_name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message="Incorrect name. Names can only contain alphabets, '-' and (space)", regex='^[A-Za-z]{2}(?:[-\\s]?[A-Za-z]+)*$')])),
                ('dob', models.DateField(validators=[api.utils.validate_date])),
            ],
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('first_name', 'last_name'), name='customer_unique_fullname', violation_error_message='Customer with same first and last names already exists'),
        ),
    ]
